### ISSUE TITLE
Edição 256 (9 a 15 de junho de 2015)

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/semanario#1]
[Código-fonte](semanario-256.md)

Etapas a completar:
- [x] transformar texto em markdown
- [ ] traduzir
  - [x] Fundraising campaign for new server hardware ‒ @vgeorge 
  - [ ] Mapping ‒ @alexandre-mbm
  - [x] Community ‒ @alexandre-mbm
  - [x] Imports ‒ @alexandre-mbm
  - [x] Events ‒ @jgpacker 
  - [x] Humanitarian OSM ‒ @jgpacker 
  - [x] Maps ‒ @jgpacker 
  - [x] Software ‒ @jgpacker 
  - [x] Did you know... ‒ @jgpacker 
  - [ ] Other "geo" things  ‒ @vgeorge 
- [ ] revisar
  - [ ] Fundraising campaign for new server hardware ‒ @jgpacker 
  - [ ] Mapping ‒ @vgeorge 
  - [ ] Community ‒ @vgeorge 
  - [ ] Imports ‒ @vgeorge
  - [ ] Events ‒ @alexandre-mbm
  - [ ] Humanitarian OSM ‒ @alexandre-mbm
  - [ ] Maps ‒ @alexandre-mbm
  - [ ] Software ‒ @alexandre-mbm
  - [ ] Did you know... ‒ @alexandre-mbm
  - [ ] Other "geo" things  ‒ @jgpacker 
- [ ] publicar

No site do WeeklyOSM: [em inglês](http://www.weeklyosm.eu/archives/4205), [em português](http://www.weeklyosm.eu/pt/archives/4205)

**Comment by vgeorge** [comment]
Acho melhor quebrar cada tarefa em um issue e colocar no milestone 256.

**Comment by alexandre-mbm** [comment]
Eu pensei nisso. Podem ser geradas por script. Seria melhor do que a lista de tópicos (coisas a fazer) que acaba de ser editada acima?

_Update_

Sim, acho que seria. O script já atribuiria as issues! Faço?

**Comment by vgeorge** [comment]
Acho melhor. Mas não precisa de script, é só lembrar de criar quatro issues das tarefas mínimas para cada nova edição: converter, traduzir, revisar, publicar. Podemos documentar isso no README.

**Comment by alexandre-mbm** [comment]
Eu não me referia aos quatros passos. Estava pensando assim:

## Milestone 256

Issue **Edição 256 / Conversão**
(atribuída a fulano)

Issue **Edição 256 / Fulano**
(atribuída a fulano)

Traduzir:
- [ ] Seção A
- [ ] Seção B

Revisar:
- [ ] Seção C
- [ ] Seção D

Issue **Edição 256 / Sicrano**
(atribuída a sicrano)

Traduzir:
- [ ] Seção C
- [ ] Seção D

Revisar:
- [ ] Seção E
- [ ] Seção F

Issue **Edição 256 / Beltrano**
(atribuída a beltrano)

Traduzir:
- [ ] Seção E
- [ ] Seção F

Revisar:
- [ ] Seção A
- [ ] Seção B

Issue **Edição 256 / Publicação**
(atribuída a fulano)

"Conversão" e "Publicação" seriam atribuídas rotativamente (a cada semana) por alguém que pegaria menos tradução e menos revisão naquela semana.

O script calcularia as divisões pelo número de palavras, atribuiria as seções, e popularia o milestone no GitHub, com base em versão TXT copiada-colada do Wordpress para seu INPUT.

**Comment by alexandre-mbm** [comment]
Não pensei as atribuições com cuidado.
Estamos em meio de caminho e eu praticamente só joguei dados.

**Comment by alexandre-mbm** [comment]
**Minha proposta:** vamos usar kanban e auto-atribuição de issues.

Amanhã pela manhã vocês terão um exemplo completo neste repositório. O correto uso do kanban evitará muitos conflitos e tornará a comunicação da equipe muito eficiente.

**Comment by vgeorge** [comment]
Acho complicado demais controlar cada tarefinha aqui. Vamos tentar fazer sem elas e se der conflito nas edições revemos?

**Comment by alexandre-mbm** [comment]
Você conhece waffle.io? Quando falo de ter um kanban, falo de usar ele. O "complicado" seria alimentar o GitHub com issues a cada semana (dê uma olhada nos milestones). Teria ser automatizado. Depois de criadas as issues, o uso do kanban no waffle.io seria muito natural.

**Comment by vgeorge** [comment]
Vamos tentar mais simples, não podemos ficar mais tempo gerenciando no Github do que fazendo. A idéia dos PR é que um revise o do outro, você pode revisar o meu e aceitar ou não?

**Comment by alexandre-mbm** [comment]
> não podemos ficar mais tempo gerenciando no Github do que fazendo

Isso é verdade, com toda certeza. Por isso da automatização da criação de issues. O kanban eliminaria o desperdício de tempo com a interface do GitHub na lida com atualização de issues.

> você pode revisar o meu e aceitar ou não?

Eu estava pensando em revisar os que que marquei lá em cima, na abertura desta issue. Então @jgpacker seria o revisor de "Fundraising campaign for new server hardware".

**Comment by alexandre-mbm** [comment]
~~Exemplo: https://waffle.io/cadanimal/cadanimal.github.io~~
Ou melhor: https://waffle.io/OSMBrasil/semanario?milestone=256

**Comment by vgeorge** [comment]
Já revisei o PR do John.

**Comment by alexandre-mbm** [comment]
Criei todo o milestone 256 usando um script que precisa ser polido. Estou colocando o script num repositório separado. A ideia é que usemos **kanban** por [waffle.io](https://waffle.io). Percebam que há a possibilidade da pessoa filtrar o seu kanban. O **arrasto** no kanban mantém o estado de cada issue atualizado!
- https://waffle.io/OSMBrasil/semanario
- https://waffle.io/OSMBrasil/semanario?milestone=256
- https://waffle.io/OSMBrasil/semanario?milestone=256&assigned=jgpacker
- https://waffle.io/OSMBrasil/semanario?milestone=256&assigned=vgeorge

Estou fechando esta issue porque ela perdeu a utilidade para a qual foi idealizada. Estou atualizando o `README.md` quanto a isso.

**O arrasto no kanban é ligeiro!**
**O script nos fará dar conta de popular o GitHub de issues rapidamente, a cada semana.**

---

PS.: chamando @jgpacker para ler este comentário.
